services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - data_volume:/data
    networks:
      - coffee-net

  generator:
    image: ubuntu:22.04
    working_dir: /data
    volumes:
      - data_volume:/data
      - ./scripts:/scripts
    command: sh -c "apt update && apt install -y bash && /scripts/generate_data.sh"
    networks:
      - coffee-net

networks:
  coffee-net:
    driver: bridge

volumes:
  data_volume: